services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx
  website:
    build:
      context: ./website/
    expose:
      - "3000"
    develop:
      watch:
        - path: ./website/
          action: rebuild
