services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/app/staticfiles
    develop:
      watch:
        - path: ./nginx/
          action: rebuild
  website:
    build:
      context: ./website/
    expose:
      - "3000"
    develop:
      watch:
        - path: ./website/
          action: rebuild
  api:
    build:
      context: ./api/
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - staticfiles:/app/staticfiles
    develop:
      watch:
        - path: ./api/
          action: rebuild
volumes:
  staticfiles:
