services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/app/staticfiles
    develop:
      watch:
        - path: ./nginx/
          action: rebuild
  website:
    build:
      context: ./website/
    expose:
      - $WEBSITE_PORT
    develop:
      watch:
        - path: ./website/
          action: rebuild
  api:
    build:
      context: ./api/
    command: gunicorn api.wsgi:application --bind $API_HOST:$API_PORT
    expose:
      - $API_PORT
    volumes:
      - staticfiles:/app/staticfiles
    env_file:
      - ./api/.env
    develop:
      watch:
        - path: ./api/
          action: rebuild
volumes:
  staticfiles:
