services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    image: "socialmaker/khojomojo-nginx:latest"
  website:
    build:
      context: ./website/
    expose:
      - "3000"
    image: "socialmaker/khojomojo-website:latest"
